version: '3.7'
services:
  gela:
    container_name: gelava
    build:
      context: ./
    ports:
      - "3000:8080"
      - "3001:8080"
      - "3002:8080"
      - "3003:8080"
      - "3004:8080"
      - "3005:8080"
      - "3006:8080"